config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :trackable, :lockable, :timeoutable,
  :omniauthable, omniauth_providers: [:google_oauth2]
  
  has_many :stories
  
def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.username = auth.info.name   # assuming the user model has a name
    user.avatar = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :sign_in?
  before_action :find_story, only: [:show, :edit, :update, :destroy]

  def index
    @stories = current_user.stories.all
  end

  def new
      @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)
    if @story.save
    redirect_to stories_path, notice: 'you create a new story!'
    else
    flash.now[:notice] = "Something went wrong"
    render :new
    end
  end

  def show

  end
  
  
  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to stories_path, notice: 'Story update!'
    else
      flash.now[:notice] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    @story.destroy!
    redirect_to stories_path, notice: 'Story delete!'
  end
  
  private
  def sign_in?
    redirect_to root_path unless user_signed_in?
  end

  def find_story
    @story = current_user.stories.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :content)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def failure
   redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
welcome to Diary <br/>
<% if user_signed_in? %>
  <%= image_tag current_user.avatar if current_user.avatar %> <br/>
  <%= current_user.email %> <br/>
  <%= current_user.username %> <br/>
  <%= button_to 'Sign_out', destroy_user_session_path, method: :delete %>
<% end %>

<hr>
<% unless user_signed_in? %>
  <%= link_to 'sign_up', new_user_registration_path %> <br/>
  <%= link_to 'sign_in', user_session_path %> <br/>
<% end %>

<hr>
Starts your diary <br/>
<% if user_signed_in? %>
  <%= link_to 'diary index', stories_path %> <br/>
  <%= link_to 'Create New Diary', stories_path %> <br/>

<% end %>

<hr>

app/views/stories/_form.html.erb
hiiii
<div>
<%= form_for @story do |f| %>
  <%= f.label :title, "title" %>
  <%= f.text_field :title %> <br/>

  <%= f.label :content, "content" %>
  <%= f.text_area :content %>

  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/stories/edit.html.erb
edit your story <br/>
<%= render 'form' %>

app/views/stories/index.html.erb
<%= image_tag current_user.avatar if current_user.avatar %> <br/>
<%= current_user.email %>'s diaries list <br/>
<%= button_to 'Sign_out', destroy_user_session_path, method: :delete %>

<hr>

<%= link_to "Create Story", new_story_path %>

<hr>

<% @stories.each do |s| %>
  Title: <%= link_to s.title, story_path(s) %> <br/>
  Contnet: <%= s.content %> <br/>
  <%= button_to 'Edit', edit_story_path(s), method: :get %>
  <%= button_to 'Delete', story_path(s), method: :delete %>
  <hr>
<% end %>

app/views/stories/new.html.erb
create your story <br/>
<%= render 'form' %>

app/views/stories/show.html.erb
<%= @story.title %> <br/>
<%= @story.content %> <br/>